### ISSUE TITLE
Change the (Docker container) environment for our condor config file location and any addtional python modules.

### ISSUE THREAD

**Issue by bdklahn** [copasi/cloud-copasi#21]
Fix the following to . . .
1. point to our custom condor_config
2. include the correct path to any condor-provided Python modules.

https://github.com/copasi/cloud-copasi/blob/0376aa931e6716831f0e07c877c62c9ae4b172e6/Dockerfile#L14-L15

I don't think we need to explicitly include the normal system Python install path, as PYTHONPATH seems to ["Augment"](https://docs.python.org/3.8/using/cmdline.html#environment-variables), not replace, the normal path.

**Comment by hasanbaig** [comment]
should be: 
CONDOR_CONFIG=/home/cloudcopasi/condor/etc/condor_config

**Comment by bdklahn** [comment]
02a77e1a99cc83be44c02e6aebd5e0fe8a53d3e5
. . . should take care of this.
