### ISSUE TITLE
We should probably be using 'web_interface.apps.WebInterfaceConfig'.

### ISSUE THREAD

**Issue by bdklahn** [copasi/cloud-copasi#28]
Hello @hasanbaig 
e.g.
https://github.com/copasi/cloud-copasi/blob/02075cd51105bc1d70d05f220d753afed5eeb295/cloud_copasi/settings.py.EXAMPLE#L204-L205
(What specific issue did that reversion fix?)

The [current Django docs example](https://docs.djangoproject.com/en/4.0/intro/tutorial02/) uses . . .

```python
INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```
. . . where `polls` would be `web_interface`, in our case.

That might be how Django (currently) allows apps to report their own metadata (name, label, etc.) to any project they might become part of (rather than, maybe, requiring settings.py to set or know such details globally).

That was listed in many places as a fix for an error I was getting before (trying to recall now).
I also wonder if it could fix Issue #27, where it seems like `python manage.py migrate web_interface` doesn't even seem to know there is a `web_interface` app to do model migrations for. Has `migrate` been working fine for you lately?

**Comment by hasanbaig** [comment]
Hi @bdklahn: Okay. I was following the other ways which I mentioned in [settings.py.EXAMPLE](https://github.com/copasi/cloud-copasi/blob/02075cd51105bc1d70d05f220d753afed5eeb295/cloud_copasi/settings.py.EXAMPLE#L204-L205)

Well, I have just changed this line to "web_interface.apps.WebInterfaceConfig" and it appears to work fine. So, you can keep using this and lets update the [settings.py.EXAMPLE](https://github.com/copasi/cloud-copasi/blob/02075cd51105bc1d70d05f220d753afed5eeb295/cloud_copasi/settings.py.EXAMPLE#L204-L205) back to what you have suggested.

**Comment by hasanbaig** [comment]
I have just updated this line in [settings.py.EXAMPE](https://github.com/copasi/cloud-copasi/blob/03bdc68a4402a70c42f7ec7f182cc3b5c2a1afcb/cloud_copasi/settings.py.EXAMPLE#L204)

You may close this issue now.

**Comment by bdklahn** [comment]
Cool.
Thanks!
