### ISSUE TITLE
restructuring of folders has deep consequences

### ISSUE THREAD

**Issue by pmendes** [copasi/cloud-copasi#31]
Hi,
in setting up a clean version of cloud-copasi I'm coming across many bugs caused by the restructuring of folder structure that Brian created. The latest is the location of 'web_interface'. Originally this was ~/cloud-copasi/cloud_copasi/web_interface ; afterword it became ~cloud-copasi/web_interface. However the code is now calling pages in ~/cloud-copasi/cloud_copasi/web_interface and generating "Server Error (500)" errors on the browser.

The question now is what is easier to fix: change the structure back to what it was? or change all the references to the folders that changed place?

For the latter it would be good to generate a list of what has changed.

**Comment by hasanbaig** [comment]
I think we can keep it as is now. 

The only place to be updated left (according to my search) is this line 
https://github.com/copasi/cloud-copasi/blob/fbaa85786264d647b7c0260044e79b2477f6048c/web_interface/pools/condor_tools.py#L79

**Comment by hasanbaig** [comment]
@pmendes: I have just updated it. Please pull the changes before proceeding ahead.

**Comment by pmendes** [comment]
Thanks @hasanbaig

**Comment by pmendes** [comment]
Confirmed that your commit fixed the problem. Hope that we don't have more of these. I am going to close this issue.
